### ISSUE TITLE
node_modules folder been uploaded even if its in slsignore

### ISSUE THREAD

**Issue by dmtzs** [nya1/serverless-ignore#11]
The folder of node modules is uploaded even if its in the slsignore.
My sls ignore is like below:
```txt
node_modules/*
package.json
package-lock.json
script.py
Notas.txt
```

my package.json is like below:
```json
{
    "devDependencies": {
      "serverless-python-requirements": "^5.4.0",
      "mfa-serverless-plugin": "^0.0.5",
      "serverless-ignore": "^0.2.1",
      "serverless-plugin-scripts": "^1.0.2"
  }
}
```

Im not understanding why the folder its been uploaded even that its ignored,  also .github and .slsignore files are uploaded too. My node version is: ``16.14.2``

**Comment by dmtzs** [comment]
# Update
This happens apparently when its used the plugin of python requirements, is there something you can do to fix this?

**Comment by nya1** [comment]
Hello, to ignore the entire directory you should have only `node_modules/` (with the trailing slash)
