### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by ilyasmez** [nya1/serverless-ignore#2]
I've added the plugin as described in the README, but whenever I try to deploy, I get this error:
```
Serverless Ignore Error --------------------------------------
    Cannot read property 'file' of undefined
```
And the deployment is done **with** the files I put in `. slsignore`

---

#### Steps to reproduce:
1- Install the plugin.
2- Add a custom variable to your `serverless.yml` and make sure `ignore` is not there.
3- Create a `.slsignore` file with some files to ignore.
4- Run `serverless deploy`

You should see the error above in your console and your files won't be ignored.

**Comment by ilyasmez** [comment]
For people having this issue, you can add this to your `serverless.yml` as a workaround:

```yml
custom:
  <your other variables>
  ignore:
    file: .slsignore
```

**Comment by nya1** [comment]
thanks for the MR, pushed version 0.1.6
