### ISSUE TITLE
.slsignore file getting bundled in sls deploy zip file

### ISSUE THREAD

**Issue by MeRahulAhire** [nya1/serverless-ignore#4]
I'm trying out your plugin and noticed that it is ignoring the file as what my terminal shows
```bash
Serverless: SERVERLESS-IGNORE: Loaded .slsignore
Serverless:      - ./bucket/*
Serverless:      - ./frontend/*
Serverless:      - ./object/deleteObject.js
Serverless:      - ./object/deleteObjects.js
Serverless:      - ./object/getObject-presignedURL.js
Serverless:      - ./object/getObjectTorrent.js
Serverless:      - ./object/listObjects.js
```
but what I'm noticing is that the these files are ending up in getting bundled in `sls deploy` zip file. So I want to know is anything wrong on my part or it ignores loading these files in lambda but does gets them deployed?

**Comment by nya1** [comment]
Hello,
Double check the file paths, .slsignore file should be placed in the root directory, and the file must be listed as a relative path to the root directory, make sure you are also executing the deploy command on the same root directory.
The zip file produced should be the same that will be deployed.

**Comment by MeRahulAhire** [comment]
As far as I remembered, everything was in correct path and directory

**Comment by nya1** [comment]
Hello, have you tried the latest 0.2.1 version? if you are still experiencing the same issue can you please create a minimal reproduction with you current setup?

**Comment by MeRahulAhire** [comment]
I'll try and let you know if I'm getting that error again or not.
